[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
NDTV = "d08b9634-086a-4eae-932f-e15cd61d6088"
Network = "027a387e-e55f-4537-a155-5037e5a23bdb"
NetworkDynamic = "2ec8e4a1-edb9-4657-8cef-4d333c164b0b"

[sources]
NDTV = {path = ".."}
Network = {url = "https://github.com/statistical-network-analysis-with-Julia/Network.jl.git"}
NetworkDynamic = {url = "https://github.com/statistical-network-analysis-with-Julia/NetworkDynamic.jl.git"}

[compat]
Documenter = "1"
